### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by AidasK** [getsentry/sentry-laravel#141]
Error message was not delivered to getsentry because php script has ran out of memory. I am doing a huge select from database and it always fails. Any ideas how can I fix sentry error logger?

I am using sentry-laravel 0.9.0, php-7.2.5,  laravel 5.6, php-fpm

```
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/versions/1529938546/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 141"
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/versions/1529938546/vendor/symfony/debug/Exception/FatalErrorException.php on line 1"
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: Packets out of order. Expected 6 received 80. Packet size=34816 in Unknown:0"
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "Stack trace:"
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "#0 /var/www/versions/1529938546/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Packets out of ...', 'Unknown', 0, NULL)"
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'Packets out of ...', 'Unknown', 0, NULL)"
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "#2 {main}"
[26-Jun-2018 07:56:12] WARNING: [pool www] child 10364 said into stderr: "  thrown in Unknown on line 0"
[26-Jun-2018 07:56:43] WARNING: [pool www] child 10364 exited on signal 11 (SIGSEGV - core dumped) after 1461.092616 seconds from start
[26-Jun-2018 07:56:43] NOTICE: [pool www] child 17296 started
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 28672 bytes) in /var/www/versions/1529938546/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 141"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/versions/1529938546/vendor/symfony/debug/Exception/FatalErrorException.php on line 1"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: Packets out of order. Expected 4 received 80. Packet size=34816 in Unknown:0"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "Stack trace:"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "#0 /var/www/versions/1529938546/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Packets out of ...', 'Unknown', 0, NULL)"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'Packets out of ...', 'Unknown', 0, NULL)"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "#2 {main}"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 said into stderr: "  thrown in Unknown on line 0"
[26-Jun-2018 07:57:21] WARNING: [pool www] child 10054 exited on signal 11 (SIGSEGV - core dumped) after 1559.598685 seconds from start
[26-Jun-2018 07:57:21] NOTICE: [pool www] child 17445 started
```

**Comment by stayallive** [comment]
We have a 10Mb buffer built-in to the error logger, so it could be possible that somehow the payload exceeds that 10Mb while serializing (breadcrumbs etc.).

Is it a possibility for you to create a script that reproduces this error so we can investigate and possible fix it?

**Comment by AidasK** [comment]
I am doing one query by id which returns a single result ` File::whereId($id)->first();` and just after it `File::whereStatus($status)->get();`. 
Model looks like this:
```php
class File extends Model
{
    protected $table = 'files';

    protected $guarded = [];
}
```
I also don't have any events and debug mode is off.

**Comment by reganjohnson** [comment]
Having a similar issue - pulled too much from the database, and ran out of memory - not much in the way of additional details, but getting exceptions around these files:

```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 57344 bytes) in /var/app/current/vendor/sentry/sentry-laravel/src/Sentry/Laravel/EventHandler.php on line 102
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/app/current/vendor/symfony/debug/Exception/FatalErrorException.php on line 1
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 57344 bytes) in /var/app/current/vendor/sentry/sentry-laravel/src/Sentry/Laravel/EventHandler.php on line 102
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/app/current/vendor/sentry/sentry/src/Options.php on line 564
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 57344 bytes) in /var/app/current/vendor/sentry/sentry-laravel/src/Sentry/Laravel/EventHandler.php on line 102
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/app/current/vendor/sentry/sentry/src/Options.php on line 564
```

Have since fixed the queries.

**Comment by ChrisThompsonTLDR** [comment]
We just updated to v1.0.0 and are encountering this error in our migrations.  We have a few migrations that import data from an old system into a Laravel based system.

Prior to updating to Sentry 1.0.0 and Laravel 5.8, we didn't encounter this issue.  Now we are.

```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes) in /var/www/www.domain.com/tacohut/vendor/sentry/sentry/src/State/Scope.php on line 215

   Symfony\Component\Debug\Exception\FatalErrorException  : Allowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes)

  at /var/www/www.mynewmarkets.com/chris/vendor/sentry/sentry/src/State/Scope.php:215
    211|      */
    212|     public function addBreadcrumb(Breadcrumb $breadcrumb, int $maxBreadcrumbs = 100): self
    213|     {
    214|         $this->breadcrumbs[] = $breadcrumb;
  > 215|         $this->breadcrumbs = \array_slice($this->breadcrumbs, -$maxBreadcrumbs);
    216|
    217|         return $this;
    218|     }
    219|
```

We've tried to turn off sentry above the migration and then back on, but it doesn't seem to work
```
config(['sentry.dsn' => null]);
```

**Comment by ChrisThompsonTLDR** [comment]
Possibly consider turning off sql bindings if dsn isn't set?

https://github.com/getsentry/sentry-laravel/blob/c75ac24de58a204c88b2ace1a904f7b5e7ef54e4/src/Sentry/Laravel/EventHandler.php#L68

My assumption is that if a dsn isn't configured, Sentry shouldn't be doing anything.

**Comment by stayallive** [comment]
Yes we are (going) to do that: https://github.com/getsentry/sentry-laravel/blob/5a46f3f2664732f5a94d5fd0a45bb1322d25a3fb/src/Sentry/Laravel/ServiceProvider.php#L28-L30

However setting the `config(['sentry.dsn' => null])` at runtime will not work because Sentry will already have loaded with whatever you had in your config before. The config parameters are not "reactive" so we don't know when you changed it.

You can try to lower the amount of breadcrumbs from your `config/sentry.php` by setting `max_breadcrumbs` to anything lower than 100 (since 100 is the default).

**Comment by stayallive** [comment]
Hi all, we now have configuration parameters to prevent OOM errors if the default breadcrumb collection is causing issues for you, little late but it might help!

https://github.com/getsentry/sentry-laravel/blob/master/config/sentry.php#L10-L22
