### ISSUE TITLE
Log channel might not be configured correctly

### ISSUE THREAD

**Issue by dwightwatson** [getsentry/sentry-laravel#285]
Hi there - I've been debugging my app not receiving exceptions in Sentry. I've been using the log channel implementation for a while and it *did* work but doesn't appear to any more.

I'm using a stack channel that logs to daily log files on the server as well as Sentry. I noticed that after each error in the log file there was another error which seems to indicate that the Sentry channel was not able to be instantiated...

```
[2019-10-16 21:06:45] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Psr\\Log\\InvalidArgumentException(code: 0): Level \"NULL\" is not defined, use one of: 100, 200, 250, 300, 400, 500, 550, 600 at /home/forge/app/releases/20191016100104/vendor/monolog/monolog/src/Monolog/Logger.php:419)
[stacktrace]
#0 /home/forge/app/releases/20191016100104/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php(53): Monolog\\Logger::toMonologLevel(NULL)
#1 /home/forge/app/releases/20191016100104/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php(33): Monolog\\Handler\\AbstractHandler->setLevel(NULL)
#2 /home/forge/app/releases/20191016100104/vendor/sentry/sentry-laravel/src/Sentry/Laravel/SentryHandler.php(45): Monolog\\Handler\\AbstractHandler->__construct(NULL, true)
#3 /home/forge/app/releases/20191016100104/vendor/sentry/sentry-laravel/src/Sentry/Laravel/LogChannel.php(17): Sentry\\Laravel\\SentryHandler->__construct(Object(Sentry\\State\\Hub), NULL, true)
#4 /home/forge/app/releases/20191016100104/vendor/sentry/sentry-laravel/src/Sentry/Laravel/ServiceProvider.php(60): Sentry\\Laravel\\LogChannel->__invoke(Array)
#5 /home/forge/app/releases/20191016100104/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(208): Illuminate\\Log\\LogManager->Sentry\\Laravel\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#6 /home/forge/app/releases/20191016100104/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(188): Illuminate\\Log\\LogManager->callCustomCreator(Array)
#7 /home/forge/app/releases/20191016100104/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve('sentry')
#8 /home/forge/app/releases/20191016100104/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get('sentry')
#9 /home/forge/app/releases/20191016100104/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(87): Illuminate\\Log\\LogManager->driver('sentry')
#10 /home/forge/app/releases/20191016100104/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(233): Illuminate\\Log\\LogManager->channel('sentry')
#11 [internal function]: Illuminate\\Log\\LogManager->Illuminate\\Log\\{closure}('sentry', 1)
...rest of stack trace omitted
```

I could be wrong, but I think the error is coming from [`LogChannel#L17`](https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/LogChannel.php#L17) - if the user doesn't provide a log level in their channel configuration it defaults to `null`. It looks like [`SentryHandler`'s constructor](https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/SentryHandler.php#L43) is meant to default the level to `Logger::DEBUG` if not provided, but because it receives null it uses that instead - which causes the error above.

The fix for the end-user now is to actually specify the level when registering the channel. The documentation currently says this is optional.

```php
'sentry' => [
    'driver' => 'sentry',
    'level' => 'debug',
],
```

However this should be fixed in the log channel. I suspect it's as simple as changing the second argument. Happy to PR this if wanted.

```php
$config['level'] ?? Logger::DEBUG
```

**Comment by stayallive** [comment]
Fixed in the `1.4.1` release that just went live.
