### ISSUE TITLE
Error with new breadcrumb feature

### ISSUE THREAD

**Issue by pedrommone** [getsentry/sentry-laravel#40]
I saw that now we can track breadcrumbs and thats pretty cool! But, unfortunately, one of our Laravel services have broke when we updated its dependencies. It was so painful that it even break the Exception Handler.

We removed the Sentry from the Exception Handler and got this log...

```
[2016-12-09 00:44:24] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Auth\AuthManager::createDriver(), 0 passed in /data/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and exactly 1 expected in /data/www/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:16
Stack trace:
#0 /data/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(87): Illuminate\Auth\AuthManager->createDriver()
#1 /data/www/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(18): Illuminate\Support\Manager->createDriver(NULL)
#2 /data/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Auth\AuthManager->createDriver(NULL)
#3 /data/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(137): Illuminate\Support\Manager->driver()
#4 /data/www/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php(85): Illuminate\Support\Manager->__call('check', Array)
#5 /data/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Sentry\SentryLaravel\SentryLaravelServiceProvider->Sentry\SentryLaravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#6 /data/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure), Array)
#7 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('sentry', Array)
#8 /data/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1167): Illuminate\Foundation\Application->make('sentry')
#9 /data/www/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php(51): Illuminate\Container\Container->offsetGet('sentry')
#10 /data/www/vendor/sentry/sentry-laravel/src/Sentry/SentryLaravel/SentryLaravelServiceProvider.php(45): Sentry\SentryLaravel\SentryLaravelServiceProvider->bindEvents(Object(Illuminate\Foundation\Application))
#11 [internal function]: Sentry\SentryLaravel\SentryLaravelServiceProvider->boot()
#12 /data/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#14 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Sentry\SentryLaravel\SentryLaravelServiceProvider))
#15 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Sentry\SentryLaravel\SentryLaravelServiceProvider), 21)
#16 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#17 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#18 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#19 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#20 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#21 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#22 /data/www/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#23 {main}  
```

As you can see in the log, the issue was about the AuthManager, and the AuthManager use some session stuff that we've disabled :(.

So, we removed the SentryServiceProvider and everything worked again. We're using PHP 7.1 with Laravel 5.1.

**Comment by gabeguz** [comment]
This fix has the side effect of spamming the console (stderr) with messages like: 
```
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
.sentry.breadcrumbs error=Class auth does not exist
```
just fyi.

**Comment by stayallive** [comment]
There is now a configuration option (since 0.7.0) to disable resolving the authenticated user for the user context, this should fix this.

```diff
<?php

return array(
    'dsn' => env('SENTRY_DSN', ''),

    // capture release as git sha
    // 'release' => trim(exec('git log --pretty="%h" -n1 HEAD')),

    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => true,
+
+   // Capture default user context
+   'user_context' => true,
);
```
