### ISSUE TITLE
Sentry v2 not working with php 7.3.x Call to undefined function Sentry\str_starts_with()

### ISSUE THREAD

**Issue by mariosvasiliou** [getsentry/sentry-laravel#468]
It's been months since I have this error and I thought that was fixed after so many versions released... I was in v1.7 before...and I have updated to v2.3.1 and now it's not working again. The problem is that you are using PHP functions from PHP v8 even though it says that v2 is working with PHP 7.2 and above.

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
PHP

### Steps to Reproduce

Use PHP v7.3.x with sentry Laravel v2.3.1
Add in composer.json 
```
"replace": {
  "symfony/polyfill-php74": "*",
  "symfony/polyfill-php80": "*"
}
```
Try to send an exception

### Expected Result

Send exception normally to Sentry

### Actual Result

Exception 5xx and this on logs

```
2021/03/23 19:10:14 [error] 2081#2081: *92239498 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Sentry\str_starts_with() in /vendor/sentry/sentry/src/FrameBuilder.php:101
Stack trace:
#0  /vendor/sentry/sentry/src/FrameBuilder.php(67): Sentry\FrameBuilder->stripPrefixFromFilePath('...')
#1 /vendor/sentry/sentry/src/StacktraceBuilder.php(66): Sentry\FrameBuilder->buildFromBacktraceFrame('...', 101, Array)
#2 /vendor/sentry/sentry/src/StacktraceBuilder.php(46): Sentry\StacktraceBuilder->buildFromBacktrace(Array, '..., 101)
#3/vendor/sentry/sentry/src/Client.php(304): Sentry\StacktraceBuilder->buildFromException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#4 /vendor/sentry/sentry/src/Client.php(218): Sentry\Client->addThrowableToEvent(Object(Sentry\Event), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#5 /...PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Sentry\str_starts_with() in /vendor/sentry/sentry/src/FrameBuilder.php:101
Stack trace:
#0 /vendor/sentry/sentry/src/FrameBuilder.php(67): Sentry\FrameBuilder->stripPrefixFromFilePath('...')
#1 /vendor/sentry/sentry/src/StacktraceBuilder.php(73): Sentry\FrameBuilder->buildFromBacktraceFrame('...', 101, Array)
#2 /vendor/sentry/sentry/src/StacktraceBuilder.php(46): Sentry\StacktraceBuilder->buildFromBacktrace(Array, '...', 101)
#3 /vendor/sentry/sentry/src/Client.php(304): Sentry\StacktraceBuilder->buildFromException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
```

**Comment by stayallive** [comment]
You are replacing `symfony/polyfill-php80` which blocks it from installing.

`str_starts_with` was introduced in PHP 8.0, so that is why that polyfill is there.

So this is a "bug" by your own making :) 

Keep the PHP 8 polyfill and everything works as expected!

**Comment by stayallive** [comment]
I am closing this issue because of inactivity, if there is still an issue please re-open / open a new issue so we can investigate 👍

**Comment by ahjwen** [comment]
Wow, that's great. Thank you very much~
