### ISSUE TITLE
Laravel 5.4 class sentry does not exist

### ISSUE THREAD

**Issue by alanaasmaa** [getsentry/sentry-laravel#61]
Hello, 

So im using laravel 5.4 and WSL for development. I try to use composer install over git bash (windows 10),
im getting `Class sentry does not exist` .

```
PHP Fatal error:  Uncaught ReflectionException: Class Sentry does not exist in C:\Users\AlanAasmaa\Code\xxx\vendor\laravel\framework\src\Illuminate\Container\Container.php:719
Stack trace:
#0 C:\Users\AlanAasmaa\Code\xxx\vendor\laravel\framework\src\Illuminate\Container\Container.php(719): ReflectionClass->__construct('Sentry')
#1 C:\Users\AlanAasmaa\Code\xxx\vendor\laravel\framework\src\Illuminate\Container\Container.php(598): Illuminate\Container\Container->build('Sentry')
#2 C:\Users\AlanAasmaa\Code\xxx\vendor\laravel\framework\src\Illuminate\Container\Container.php(567): Illuminate\Container\Container->resolve('Sentry')
#3 C:\Users\AlanAasmaa\Code\xxx\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(702): Illuminate\Container\Container->make('Sentry')
#4 C:\Users\AlanAasmaa\Code\xxx\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(107): Illuminate\Foundation\Application->make('Sentry')
#5 C:\Users\AlanAasmaa\Code\xxx\app\Exceptions\Handler.php(36): app('Sentry')
# in C:\Users\AlanAasmaa\Code\xxx\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 719
```

I have debugged that the line is in app\Exceptions\Handler.php

```
       if ($this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }
```

I think the error is somehow with laravel interface binding ?

**Comment by alanaasmaa** [comment]
I reinstalled. removed vendor directory removed all kind of caches and it fixed the problem.
