### ISSUE TITLE
Sentry tracing throws exception, while using octane&bref

### ISSUE THREAD

**Issue by korridor** [getsentry/sentry-laravel#716]
### Environment

laravel: 10.13.5
laravel-sentry: 3.5.0
PHP: 8.2

With Laravel Octance on AWS Lambda

### Steps to Reproduce

1. Deploy Laravel application with [bref.sh]((https://bref.sh/)) on AWS lambda
2. Activate sentry tracing

This is probably hard to reproduce for the maintainer.
I can do that, but I would need a bit more information about what this exception means.

### Expected Result

No exception in sentry, because of tracing.

### Actual Result

```
Error: Call to a member function finish() on null
#17 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(230): Sentry\Laravel\Tracing\Middleware::finishTransaction
#16 /vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(112): Sentry\Laravel\Tracing\Middleware::Sentry\Laravel\Tracing\{closure}
#15 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#14 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\Util::unwrapIfClosure
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\Container\BoundMethod::callBoundMethod
#12 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::call
#11 /vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\Container::call
#10 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1250): Illuminate\Foundation\Application::terminate
#9 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\Foundation\Http\Kernel::terminate
#8 /vendor/laravel/octane/src/ApplicationGateway.php(51): Laravel\Octane\ApplicationGateway::terminate
#7 /vendor/laravel/octane/src/Worker.php(110): Laravel\Octane\Worker::handle
#6 /vendor/bref/laravel-bridge/src/Octane/OctaneClient.php(50): Bref\LaravelBridge\Octane\OctaneClient::handle
#5 /vendor/bref/laravel-bridge/src/Http/OctaneHandler.php(41): Bref\LaravelBridge\Http\OctaneHandler::handleRequest
#4 /vendor/bref/bref/src/Event/Http/HttpHandler.php(25): Bref\Event\Http\HttpHandler::handle
#3 /vendor/bref/bref/src/Runtime/Invoker.php(24): Bref\Runtime\Invoker::invoke
#2 /vendor/bref/bref/src/Runtime/LambdaRuntime.php(89): Bref\Runtime\LambdaRuntime::processNextEvent
#1 /vendor/bref/bref/src/FunctionRuntime/Main.php(37): Bref\FunctionRuntime\Main::run
#0 /opt/bref/bootstrap.php(17): null
```

**Comment by cleptric** [comment]
Version [3.5.1](https://github.com/getsentry/sentry-laravel/releases/tag/3.5.1) was released, which should fix this issue. Sorry about this!

**Comment by korridor** [comment]
Thanks for the prompt fix! :)
